### ISSUE TITLE
issue with pictures not working

### ISSUE THREAD

**Issue by c3rsk** [Kycklingar/pbooru-downloader#5]
![Screenshot 2023-08-08 211949](https://github.com/Kycklingar/pbooru-downloader/assets/141792795/9ddf5a5d-575b-4de7-9873-80e40c367f38)

how can this be fixed?

**Comment by c3rsk** [comment]
its like that with any of the files i download. is there any way to get the images to show? or be supported?

**Comment by Kycklingar** [comment]
Please provide command arguments used.

**Comment by c3rsk** [comment]
download.py --url http://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion/ --gateway http://localhost:8080 --proxy socks5h://localhost:9150 -a creator:trunchbull trunch
These were the exact commands On Aug 9, 2023 11:58 AM, Kycklingar ***@***.***> wrote:
Please provide command arguments used.

**Comment by Kycklingar** [comment]
Ok, I've pushed a fix to master.

**Comment by c3rsk** [comment]
The picture shows now. Thank you. :)On Aug 9, 2023 12:48 PM, Kycklingar ***@***.***> wrote:
Ok, I've pushed a fix to master.
